- name: Assign default value if we don't pass any value to the variable
  hosts: localhost #no need to declare it in inventory.ini file. Wherever we install ansible its a loaclhost
  tasks: #list of tasks/modules/collections
  - name: Print number
    debug: 
      msg: "Enter number {{NUM | default(10)}}"

- name: Convert text from lower case to upper case
  hosts: localhost #no need to declare it in inventory.ini file. Wherever we install ansible its a loaclhost
  tasks: #list of tasks/modules/collections
  - name: lower to upper case
    vars:
      greeting: hey
    debug: 
      msg: "Text {{greeting | upper}}"


- name: Convert text from upper case to lower case
  hosts: localhost #no need to declare it in inventory.ini file. Wherever we install ansible its a loaclhost
  tasks: #list of tasks/modules/collections
  - name: upper to lower case
    vars:
      greeting: HEY
    debug: 
      msg: "Text {{greeting | lower}}"


- name: Remove duplicates from the list
  hosts: localhost #no need to declare it in inventory.ini file. Wherever we install ansible its a loaclhost
  tasks: #list of tasks/modules/collections
  - name: remove duplicates 
    vars:
      Numbers: [1,2,3,4,1,4,5,6,6]
    debug: 
      msg: "Text {{Numbers | unique}}"


- name: Max & Min number from the list
  hosts: localhost #no need to declare it in inventory.ini file. Wherever we install ansible its a loaclhost
  tasks: #list of tasks/modules/collections
  - name: Max & Min numbers 
    vars:
      Numbers: [1,2,3,4,1,4,5,6,6]
    debug: 
      msg: "Min number is: {{Numbers | min}}, Max number is: {{Numbers | max}}"


- name: dictionary/map to items/list conversion
  hosts: localhost #no need to declare it in inventory.ini file. Wherever we install ansible its a loaclhost
  vars:
    experience:
      course: Devops with AWS
      trainer: Sidhartha
  tasks: #list of tasks/modules/collections
  - name: dictionary/map to items before convert
    debug: 
      msg: "Before conversion: {{experience}}"

  - name: dictionary/map to items after convert
    debug: 
      msg: "After conversion: {{experience | dict2items}}"



- name: items/list to dictionary/map conversion
  hosts: localhost #no need to declare it in inventory.ini file. Wherever we install ansible its a loaclhost
  vars:
    experience:
    - course
    - trainer
  tasks: #list of tasks/modules/collections
  - name: before convert
    debug: 
      msg: "Before conversion: {{experience}}"

  - name: after convert
    debug: 
      msg: "After conversion: {{experience | items2dict}}"