- name: Assign default value if we don't pass any value to the variable
  hosts: localhost #no need to declare it in inventory.ini file. Wherever we install ansible its a loaclhost
  tasks: #list of tasks/modules/collections
  - name: Print number
    debug: 
      msg: "Enter number {{NUM | default(10)}}"

- name: Convert text from lower case to upper case
  hosts: localhost #no need to declare it in inventory.ini file. Wherever we install ansible its a loaclhost
  tasks: #list of tasks/modules/collections
  - name: lower to upper case
    vars:
      greeting: hey how r u doing
    debug: 
      msg: "Enter number {{greeting | upper}}"


- name: Convert text from upper case to lower case
  hosts: localhost #no need to declare it in inventory.ini file. Wherever we install ansible its a loaclhost
  tasks: #list of tasks/modules/collections
  - name: upper to lower case
    vars:
      greeting: hey how r u doing
    debug: 
      msg: "Enter number {{greeting | lower}}"