- name: Install packages using loop
  hosts: localhost #no need to declare it in inventory.ini file. Wherever we install ansible its a loaclhost
  become: yes
  tasks: #list of tasks/modules/collections
  - name: Install packages from the list
    ansible.builtin.dnf:  #If i want this to work in all distributions then use this package other wise yum or dnf
      name: "{{item}}"
      state: latest 
    loop:
    - mysql
    - git
    - postfix